name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t git.systementor.se/yacloud/stefan3stefan240530 .
    - name: Login
      run: docker login -u yacloud -p yacloud1 https://git.systementor.se
    - name: Build the Docker image
      run: docker push git.systementor.se/yacloud/stefan3stefan240530
      
